<a href="https://colab.research.google.com/github/CHARAN452/Numpy_notes/blob/main/Numpy_charan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is Numpy ?
>it is a core library for scientific computing in python

the main object of the python is array ?
>Array

What is Numpy array?
> Array's are high performance multidimensional objects which is designed specially to maths operations

What are all different use cases?
>  1.Dot product / Inner product
> 2. Matrix multiplication
> 3. Element wise matrix product
> 4. Solving the linear systems
> 5. inverse
> 7. Determinent
> 8. Statastics


#installation of Numpy
to install my package we need to use pip

what is pip
> pip is python package manager

> !pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
#how many types of data structures do we have in numpy array's
# 1D --> array's with zero columns and specific rows --> axis is 0(rows)
# 2D --> Array's are with columns and rows --> axis 0 and axis 1(rows and columns)
# 3D --> Multidimensonal arrays with axis 0(row) ,axis 1(col) ,axis 2(stepper)


In [ ]:
#Array's are ordered immutable,also it allows the duplicate data


#Central object in numpy is Array's

In [ ]:
#how can we create an array
#array's are created from existing data
#1D array
a=np.array([1,2,3,4,5,6,6])
print(a)
print(type(a))

[1 2 3 4 5 6 6]
<class 'numpy.ndarray'>


In [ ]:
#i want to see the shape of the array
a.shape
#find the dtype of the numpy array
a.dtype
#find the dimension of array
a.ndim
# i want to know the no of elements in numpy array
a.size
print(len(a))
#i want to know the size in bytes of each element
a.itemsize

7


8

essential methods to create array

In [ ]:
#cerate a array from tuple
t=(1,2,3,4,5,6)
a=np.array(t)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [ ]:
#create a array from tuple
d1={'name':'Charan',
    'age':22

}
print(d1)
h=np.array(d1)
h

{'name': 'Charan', 'age': 22}


array({'name': 'Charan', 'age': 22}, dtype=object)

In [ ]:
a={7,62,3,4,4,5,6}
s=np.array(a)
s

array({3, 4, 5, 6, 7, 62}, dtype=object)

array is ordered


In [ ]:
#essetial methods to access
k=np.array([1,2,3,4])
print(k[0])
print(k[1:3])
print(k[::-1])

1
[2 3]
[4 3 2 1]


In [ ]:
#array are immutable  :- we can replace the items but we cannot add or remove the items
#replace '3' with '6'
k[2]=6
print(k)

[1 2 6 4]


Element wise mathematical operation

In [ ]:
b=np.array([6,7,8,9])
b
#when we apply arthmetic operations on array but array's has to be in same length
#TASk : apply all the arthemetic operationd


array([6, 7, 8, 9])

In [ ]:
#what is vector addition
#> when we applying the addition operation on array's with same number of elements in both array's is known as vector addition


In [ ]:
#what is the difference btw array's and list

l=[1,2,3]
a=np.array(l)
#adding the elements in list
l.append(4)
l
#adding in array
"""a.append(5)
a"""

'a.append(5)\na'

In [ ]:
#NOTE : arrays are faster than the list,tuple,set,dictionary because it had fixed memory size
#find the sqrt of the below array
a2=np.array([2,3,5,6,7])
print(np.sqrt(a2))

[1.41421356 1.73205081 2.23606798 2.44948974 2.64575131]


In [ ]:
#np.append it new items into the new array
a3=np.append(l,a2)
a3

array([1, 2, 3, 4, 2, 3, 5, 6, 7])

# Dot product

In [ ]:
a = np.array([1,2])
b=np.array([3,4])
dot=0
for i in range(len(a)):
  dot=dot+a[i]*b[i]
print(dot)

11


In [ ]:
#what is dot product
#dot product is a vector  multiplication of arrays and sum of the results


In [ ]:
c=a*b
c
d=np.sum(c)
d

11

In [ ]:
#another method
e=a.dot(b)
e

11

In [ ]:
f=a@b
f

11

# 11-02-2025

**Multi dimensional**

In [ ]:
import numpy as np

In [ ]:
#create a 2 dimensional array
a=np.array([[1,3,4,5,6],[8,9,3,43,234]])
print(a)

print(a.shape)

[[  1   3   4   5   6]
 [  8   9   3  43 234]]
(2, 5)


In [ ]:
#How to access the elements from 2d array
#[row_index:column_index]
print(a[0])
#i want to access particular value
print(a[1,1])

[1 3 4 5 6]
9


In [ ]:
print(a[1,2])

3


In [ ]:
#how can i print the entire 1st column values
b=np.array([[22,33,44,55],[66,77,88,99],[10,20,30,40]])
print(b)
print(b[2])
print(b[:,1])#to print elements from the column

[[22 33 44 55]
 [66 77 88 99]
 [10 20 30 40]]
[10 20 30 40]
[33 77 20]


In [ ]:
print(b[1,:])
print(b[2,:])

[66 77 88 99]
[10 20 30 40]


In [ ]:
#Transposs : converts the rows into columns and columns in to rows
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(a.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
#Matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
#applying dot product on above arrays
c=np.dot(a,b)
print(c)
d=a@b
d

[[13 16]
 [29 36]]


array([[13, 16],
       [29, 36]])

In [ ]:
#How to find the inverse of the Array a?
a=np.array([[1,2],[3,4]])
d=np.linalg.inv(a)
d


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#print the diagonal of array a
f=np.diag(a)
f


array([1, 4])

In [ ]:
#Diagonal on vector returns the matrix
h=np.diag([1,4,5])
print(h)#it prints the diagonal matrix

[[1 0 0]
 [0 4 0]
 [0 0 5]]


# indexinf,Slicing,Boolean Indexing

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.ndim)


2


In [ ]:
#How can we print 2 column all values
print(a[:,1])
print(a[0:3,3:4])
print(a[:,-1:])#array in 2D

[ 2  6 10]
[[ 4]
 [ 8]
 [12]]
[[ 4]
 [ 8]
 [12]]


In [ ]:
#print 11 from above array
print(a[2,2])

11


**Boolean**

In [ ]:
#print the numbers

In [ ]:
#np.where(condition,true,false)
a=np.array([10,20,30,35,37,66,33,4,5,40,54])
b=np.where(a%2==0,a,0)
print(b)

[10 20 30  0  0 66  0  4  0 40 54]


In [ ]:
#in an array compute the indexes where the condition is true
a=np.array([10,20,30,35,37,66,33,4,5,40,54])
#np.argwhere()
eve=np.argwhere(a%2==0).flatten()#flatten() is used to make the output in horizontal way
eve
eve_a=a[eve]
print(eve_a)

[10 20 30 66  4 40 54]


Reshaping of the array

In [ ]:
#create a range of array
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#print the range of arrays from 1 to 10
a=np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#reshape the above array in to 3 rows and 3 columns
#convert the above array to 5 rows and 2 columns
print(a.reshape(2,3))

ValueError: cannot reshape array of size 11 into shape (2,3)

#12-02-25
**New Axis**

In [ ]:
#why we are using np.newaxis?
#np.newaxis required when the model can be shaped in a certain manner

In [ ]:
#print the range of numbers
a=np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
#convert above array into 2 rows and 3 columns
#np.reshape
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
#new axis :- It is used to create a new axis in the data
b=a.reshape(2,3)
print(b.shape)

ValueError: cannot reshape array of size 11 into shape (2,3)

In [ ]:
#new axis
d=a[np.newaxis,:]
print(d.ndim)
print(d)
print(d.shape)

2
[[ 0  1  2  3  4  5  6  7  8  9 10]]
(1, 11)


In [ ]:
print(d.T)
print(d.ndim)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
2


In [ ]:
h=a[:,np.newaxis]
print(h)
print(h.shape)


[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
(11, 1)


**concatenation**

In [ ]:
#Concatenation
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
#combine using concatenate above 2 arrays
c=np.concatenate((a,b),axis=0)
c


#NOTE : when we concatenate according to column wise (axis=1) the array's has to be in the same length



array([[1, 2],
       [3, 4],
       [5, 6]])

**HSTACK**  **Horizontal stack**

In [ ]:
#hstack : stack array sequence horizontally
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack((a,b))
c




array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a=np.array([1,2,3,4,5,6]) #1 d array means only rows
b=np.array([3,4,5,6,7,8])
c=np.hstack((a,b))
print(c.shape)


(12,)


**VSTACK** **Vertical stack**


In [ ]:
a=np.array([1,2,3,4,5,6]) #1 d array means only rows
b=np.array([3,4,5,6,7,8])
c=np.vstack((a,b))
print(c)
print(c.shape)





[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
(2, 6)


In [ ]:
#hstack : stack array sequence horizontally
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.vstack((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#Broadcasting

In [ ]:
"""Broadcasting is a powerfull mechanism in numpy where it can works different array's of different shapes"""
a=np.array([1,2,3,4])
b=np.array([5])
c=a+b
c

array([6, 7, 8, 9])

In [ ]:
a = np.array([[1, 2], [3, 4]])
y = np.array([2, 3])  # Ensure `y` has the same length as the number of columns in `a`
print(a + y)

[[3 5]
 [5 7]]


**Copying**

In [ ]:
a=np.array([1,2,3])
b=a
b[0]=6
print(b)
#so np.copy() is used to when you make change in new array it wont impacts on original array


[6 2 3]


In [ ]:
a=np.array([4,5,67,9])
b=a.copy()
b[2]=6
print(a)
print(b)

[ 4  5 67  9]
[4 5 6 9]


**Generating Arrays**

In [ ]:
#generate an array of 0's which is having 2 rows and 3 columns
a=np.zeros((2,3),dtype=np.int32)
a
print(a.dtype)

int32


In [ ]:
a=np.ones((2,3),dtype=np.int32)
a

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

**EYE**  **identity matrix**

In [ ]:
#Generate an identity matrix
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d=np.identity(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Full command to generate identity matrix of any number**

In [ ]:
#Generate an specific numbers
e=np.full((3,3),9)
e

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

**Linspace**

In [ ]:
#linspace: splits the data into equal parts
#linspace (start,end,count_partitions)
h=np.linspace(0,10,6)
h


array([ 0.,  2.,  4.,  6.,  8., 10.])

**Random numbers()**

In [ ]:
a=np.random.random(1,9)
a
#random.random is used to generate unformly distributed


array([[0.098748  , 0.23191911, 0.73838075, 0.2959671 , 0.76578562,
        0.06647322, 0.87718107, 0.91669912, 0.93071748]])

In [ ]:
#Generate an array which is noramlly distributed
b=np.random.rand(3,2)
print(b)
print(b.mean(),b.std(),b.var())

[[0.76970858 0.80577905]
 [0.57885262 0.19460357]
 [0.70966399 0.77980485]]
0.6397354428730793 0.21245471745252767 0.04513700696783337


In [ ]:
#Genrate the random integers
c=np.random.randint(3,10,size=(3,3))

In [ ]:
c

array([[7, 3, 7],
       [6, 9, 4],
       [7, 8, 6]])

In [ ]:
#can we genarte an random integer with in a range of particular numbers
d=np.random.choice(11,size=1)
d

array([1])